name: linkfix
on:
  workflow_dispatch:
  workflow_run:
    workflows: [main to gh-pages]
    types: [completed]
jobs:
  m2p:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Fix and Push
        run: |
          git config user.name "Mdr-C-Tutorial"
          git config user.email "2972853299@qq.com"
          cd ./教程/示例代码
          python linkfix.py
          git add .
          git commit -m "linkfix"
          git push
